/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.poo;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno.saolucas
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atLista = new javax.swing.JTextArea();
        tbNumeroInteiro = new javax.swing.JLabel();
        edNumeroInteiro = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbBuscar = new javax.swing.JLabel();
        edBuscar = new javax.swing.JTextField();
        lbCodBuscar = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tbTituloExcluir = new javax.swing.JLabel();
        tbInformeCodigo = new javax.swing.JLabel();
        edExcluir = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        edNomeAlterar = new javax.swing.JPanel();
        tbTituloAlterar = new javax.swing.JLabel();
        lbInformeCodigo2 = new javax.swing.JLabel();
        edCodigoAlterar = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        tbNovoNumero = new javax.swing.JLabel();
        edNovoNumero = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btMedia = new javax.swing.JButton();
        btMaximo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btOrdenar = new javax.swing.JButton();
        btPares = new javax.swing.JToggleButton();
        btImpares = new javax.swing.JToggleButton();
        btAtualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        tbTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbTitulo.setText("GERENCIAMENTO NÚMEROS INTEIROS");

        atLista.setBackground(new java.awt.Color(0, 153, 153));
        atLista.setColumns(20);
        atLista.setRows(5);
        jScrollPane1.setViewportView(atLista);

        tbNumeroInteiro.setBackground(new java.awt.Color(0, 0, 0));
        tbNumeroInteiro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tbNumeroInteiro.setText("GERENCIAMENTO NÚMEROS INTEIROS:");

        edNumeroInteiro.setBackground(new java.awt.Color(0, 153, 153));
        edNumeroInteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNumeroInteiroActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(0, 102, 102));
        btSalvar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btListar.setBackground(new java.awt.Color(0, 102, 102));
        btListar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btListar.setText("LISTAR");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(0, 102, 102));
        btLimpar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(0, 153, 204));

        lbBuscar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbBuscar.setText("BUSCAR NÚMERO");

        edBuscar.setBackground(new java.awt.Color(0, 102, 102));
        edBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edBuscarActionPerformed(evt);
            }
        });

        lbCodBuscar.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        lbCodBuscar.setText("DIGITE O NÚMERO:");

        btBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btBuscar.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbCodBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodBuscar)
                    .addComponent(edBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscar)
                .addGap(78, 78, 78))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        tbTituloExcluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tbTituloExcluir.setText("EXCLUIR");

        tbInformeCodigo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tbInformeCodigo.setText("INFORME O CÓDIGO:");

        edExcluir.setBackground(new java.awt.Color(0, 102, 102));

        btExcluir.setBackground(new java.awt.Color(0, 102, 102));
        btExcluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbInformeCodigo)
                            .addComponent(tbTituloExcluir))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(edExcluir)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tbTituloExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbInformeCodigo)
                .addGap(17, 17, 17)
                .addComponent(edExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        edNomeAlterar.setBackground(new java.awt.Color(0, 153, 153));
        edNomeAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTituloAlterar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tbTituloAlterar.setText("ALTERAR");
        edNomeAlterar.add(tbTituloAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbInformeCodigo2.setBackground(new java.awt.Color(0, 0, 0));
        lbInformeCodigo2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbInformeCodigo2.setText("INFORME O CÓDIGO:");
        edNomeAlterar.add(lbInformeCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        edCodigoAlterar.setBackground(new java.awt.Color(0, 102, 102));
        edNomeAlterar.add(edCodigoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 106, -1));

        btAlterar.setBackground(new java.awt.Color(0, 102, 102));
        btAlterar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btAlterar.setText("ALTERAR");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        edNomeAlterar.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        tbNovoNumero.setBackground(new java.awt.Color(0, 0, 0));
        tbNovoNumero.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tbNovoNumero.setText("NOVO NÚMERO:");
        edNomeAlterar.add(tbNovoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        edNovoNumero.setBackground(new java.awt.Color(0, 102, 102));
        edNomeAlterar.add(edNovoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 106, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        btMedia.setBackground(new java.awt.Color(0, 102, 102));
        btMedia.setText("MÉDIA");
        btMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMediaActionPerformed(evt);
            }
        });

        btMaximo.setBackground(new java.awt.Color(0, 102, 102));
        btMaximo.setText("MÁXIMO");
        btMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaximoActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setText("MÍNIMO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btOrdenar.setBackground(new java.awt.Color(0, 102, 102));
        btOrdenar.setText("ORDENAR");
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMedia)
                    .addComponent(btMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btOrdenar))
                .addContainerGap())
        );

        btPares.setBackground(new java.awt.Color(0, 153, 153));
        btPares.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btPares.setText("PAREES");
        btPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParesActionPerformed(evt);
            }
        });

        btImpares.setBackground(new java.awt.Color(0, 153, 153));
        btImpares.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btImpares.setText("IMPARES");
        btImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImparesActionPerformed(evt);
            }
        });

        btAtualizar.setBackground(new java.awt.Color(0, 153, 153));
        btAtualizar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbNumeroInteiro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tbTitulo))
                                    .addComponent(edNumeroInteiro))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edNomeAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btPares, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btImpares, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btAtualizar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbTitulo)
                .addGap(18, 18, 18)
                .addComponent(tbNumeroInteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edNumeroInteiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btListar)
                        .addGap(11, 11, 11)
                        .addComponent(btLimpar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edNomeAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPares)
                    .addComponent(btImpares)
                    .addComponent(btAtualizar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        listaNumerosInteiros.alterar(Integer.parseInt(edCodigoAlterar.getText()), Integer.parseInt(edNovoNumero.getText()));
        btListar.doClick();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        listaNumerosInteiros.excluir(Integer.parseInt(edExcluir.getText()));
        btLimpar.doClick();
        btListar.doClick();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void edBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edBuscarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        atLista.setText(null);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        atLista.setText(listaNumerosInteiros.getNumero());
    }//GEN-LAST:event_btListarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        listaNumerosInteiros.salvar(Integer.parseInt(edNumeroInteiro.getText()));
        atLista.setText(null);
        atLista.setText(listaNumerosInteiros.getNumero());
        edNumeroInteiro.setText(null);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void edNumeroInteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNumeroInteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNumeroInteiroActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        int n = listaNumerosInteiros.buscar(Integer.parseInt(edBuscar.getText()));
        atLista.setText(String.valueOf(n));
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMediaActionPerformed
        double media = listaNumerosInteiros.calcularMedia();
        JOptionPane.showMessageDialog(null, "Média: " + media);
    }//GEN-LAST:event_btMediaActionPerformed

    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
        listaNumerosInteiros.ordenarLista();
        btListar.doClick();
   
    }//GEN-LAST:event_btOrdenarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int minimo = listaNumerosInteiros.getNumeroMinimo();
    JOptionPane.showMessageDialog(null, "Número Mínimo: " + minimo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaximoActionPerformed
       int maximo = listaNumerosInteiros.getNumeroMaximo();
    JOptionPane.showMessageDialog(null, "Número Máximo: " + maximo);
    }//GEN-LAST:event_btMaximoActionPerformed

    private void btParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParesActionPerformed
  JOptionPane.showMessageDialog(null, listaNumerosInteiros.getNumerosPares());
    }//GEN-LAST:event_btParesActionPerformed

    private void btImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImparesActionPerformed
        JOptionPane.showMessageDialog(null, listaNumerosInteiros.getNumerosImpares());
    }//GEN-LAST:event_btImparesActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
         btListar.doClick();
    }//GEN-LAST:event_btAtualizarActionPerformed
    GerenciamentoNumerosInteiros listaNumerosInteiros = new GerenciamentoNumerosInteiros();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atLista;
    private javax.swing.JButton btAlterar;
    private javax.swing.JToggleButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JToggleButton btImpares;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btMaximo;
    private javax.swing.JButton btMedia;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JToggleButton btPares;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edBuscar;
    private javax.swing.JTextField edCodigoAlterar;
    private javax.swing.JTextField edExcluir;
    private javax.swing.JPanel edNomeAlterar;
    private javax.swing.JTextField edNovoNumero;
    private javax.swing.JTextField edNumeroInteiro;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCodBuscar;
    private javax.swing.JLabel lbInformeCodigo2;
    private javax.swing.JLabel tbInformeCodigo;
    private javax.swing.JLabel tbNovoNumero;
    private javax.swing.JLabel tbNumeroInteiro;
    private javax.swing.JLabel tbTitulo;
    private javax.swing.JLabel tbTituloAlterar;
    private javax.swing.JLabel tbTituloExcluir;
    // End of variables declaration//GEN-END:variables
}
